### ISSUE TITLE
BioMASS version-upgrade

### ISSUE THREAD

**Issue by himoto** [pasmopy/breast_cancer#13]
#### TODO:
- [x] Bump minimal BioMASS version to 0.5.1
- [x] Update `viz.py`
- [x] Add models of four breast cancer cell lines to `models/breast/`
