### ISSUE TITLE
Cannot run `downloadTCGA`

### ISSUE THREAD

**Issue by himoto** [pasmopy/breast_cancer#31]
It seems this is due to recent changes in GDC Data Portal, which affect `TCGAbiolinks` as well (https://support.bioconductor.org/p/9143118/#9143119).

**Comment by himoto** [comment]
**TODO:**

The following files need to be updated  to be compatible with the newest GDC and TCGAbiolinks.

- [ ] [`integration.R`](https://github.com/pasmopy/breast_cancer/blob/master/transcriptomic_data/integration.R)
- [ ] `TPM_RLE_postComBat_BRCA_BREAST.tar.xz`
- [ ] [`models/breast/sample_names.txt`](https://github.com/pasmopy/breast_cancer/blob/master/models/breast/sample_names.txt)
